### PR TITLE
Make version number accessible in code

### PR DESCRIPTION
**Pull request by knatten**
This is just a suggestion, feel free to decline this or let me know if you prefer doing it in another way, such as with a shell script or Python or whatever. Or simply hard coding the version number in some header file.

~~Note that this PR conflicts with #46. If that one gets accepted, I'll rebase this one on master.~~

---

We're already making versioned releases, so let's make that version
number available in code.

There are many ways to do this, such as release scripts etc. I chose a
very simple CMake solution because the project is already using CMake
and I didn't want to introduce a dependency on a new language.

Since we're not actually building releases anywhere, but just release
the source code from the repo, I had to generate the version file inside
the source tree. The person releasing will then have to commit both
CMakeLists.txt and include/NamedType/version.hpp when bumping the
version. (As well as tagging the commit, as before.)

One downside of this approach is that there is no way to detect whether
you're using the actual x.y.z release, or if you just cloned the repo
some time after x.y.z was released and the version number hasn't been
bumped yet. This could have been solved by adding a "preview" suffix or
something like that, which is removed in official releases. But I think
that would complicate this code, and the release procedure too much for
this project. And it will anyway not be a issue for users who stick to
the official releases only.

### CODE REVIEW

**Comment by knatten** [comment]
> For my understanding, is this technique for handling versions from code common practice?

I'm not that well versed in the world of libraries, but something similar to this seems to be common in my experience.

[Catch](https://github.com/catchorg/Catch2/blob/master/include/catch.hpp#L12-L14) does
```c++
#define CATCH_VERSION_MAJOR 2
#define CATCH_VERSION_MINOR 13
#define CATCH_VERSION_PATCH 0
```

[Boost](https://www.boost.org/doc/libs/1_74_0/boost/version.hpp) does (:astonished:) :
```c++
//  BOOST_VERSION % 100 is the patch level
//  BOOST_VERSION / 100 % 1000 is the minor version
//  BOOST_VERSION / 100000 is the major version
#define BOOST_VERSION 107400
```

In Zivid where I work, [we do](https://www.zivid.com/hubfs/softwarefiles/releases/2.0.0+7c4918cf-14/doc/cpp/Version_8h.html):
```c++
#define ZIVID_CORE_VERSION_MAJOR   2
#define ZIVID_CORE_VERSION_MINOR   0
#define ZIVID_CORE_VERSION_PATCH   0
#define ZIVID_CORE_VERSION_BUILD   "7c4918cf-14"
#define ZIVID_CORE_VERSION   "2.0.0+7c4918cf-14"
```

> Also, what is the expected usage of accessing version numbers through code?

Some uses:
- Constexpr if based on which version of the library is used (or `ifdef` if you don't have constexpr if yet, which is why I went with `#define` instead of `constexpr int` or something
- Print versions of used libraries to a log or to the user
- My use case right now: There is a bug with unary operators in NamedType 1.1.0. It has been fixed, but the fix has not been released yet. I needed to add a workaround in our code in the mean time, which I want to make sure we delete when we upgrade to 1.2.0. So I wanted to do `static_assert(NAMED_TYPE_VERSION_MAJOR == 1 && NAMED_TYPE_VERSION_MINOR == 1, "Delete this workaround when we upgrade to NamedType 1.2.0" );`

**Comment by joboccara** [comment]
Ok, I see.
It seems to me there is still a pending comment in the code review, could you please have a look at it?

**Comment by knatten** [comment]
> It seems to me there is still a pending comment in the code review, could you please have a look at it?

Which comment are you talking about? I can't see any?

**Comment by joboccara** [comment]
I seemed to have sent it, can you see it now?

File: version.hpp.in [hunk 1]
```diff
@@ -0,0 +1,9 @@
+#pragma once
```
[the remark this answers is not in the document]
Comment (knatten) [reply version.hpp.in:1]: Yeah the `hpp.in` file is the template which allows CMake to generate the `.hpp` file. Normally I wouldn't add generated files to git. I agree that this is a smell!

My reasoning is as follows. There are two ways people are likely to use NamedType:
1. By cloning the repo
2. By downloading a zipped release

In 1., since this is a header only library, people are likely to just clone the repo and start using it, without actually building it. In this case, `version.hpp` will not exist, and they'll get a compilation error from [#include version.hpp](https://github.com/joboccara/NamedType/blob/8efa8cc5acc86da841b34c2837a69e9800385e6e/include/NamedType/named_type.hpp#L6).

In 2., how do you make that release? If you're making it locally or on a build server after having run the build, it would work fine to not commit `version.hpp`. It will have been built and be included in the zip. If however you just ask GitHub to zip up the repo, the file will not exist and will not be included in the zip.

Due to this, I thought it was best to commit this generated file, even though it's usually not the right thing to do.

An alternative to this whole approach would to not have the template at all, and just have the version numbers hardcoded in the file. Then you could either just update those manually before a release, or have a script do that. I understand if you prefer that.

If you want a second opinion, I can ask people on Twitter to have a look at this PR?

[the remark this answers is not in the document]
Comment (joboccara) [reply version.hpp.in:1]: I get your point, usage is currently easy by just grabbing the code, it would be a shame to lose this, so we'd want a version.hpp file.
But then since we'd have to update the version.hpp file whenever we bump the library version, I think this kills the purpose of the automatic generation, no? If you agree with that, I think we should only keep the manually updated version.hpp file.

[the remark this answers is not in the document]
Comment (knatten) [reply version.hpp.in:1]: Yeah I think that makes sense. Currently there's not much extra value in having the generation, except it makes sure you get both the separate number components and the full string correct. By doing it manually there's a theoretic possibility of forgetting one of them.

The approach I used here is more important for bigger projects where you need the version number in other places as well, like package names, documentation etc.

If you want I can change to not using generation. Maybe we could then also stop using a separate version header, and just move the macros into `named_type.hpp`. Let me know what you prefer.

[the remark this answers is not in the document]
Comment (joboccara) [reply version.hpp.in:1]: Yes I'd be in favour of removing the generation. But I think a separate file makes sense, as this is not the main use case for the library and maybe this is not the code you want to read first when you explore the main header of the library.

[the remark this answers is not in the document]
Comment (knatten) [reply version.hpp.in]: Ok! I made that change now, updated the commit message, and rebased on master while I was at it. I also added a test to make sure the version number macros and the version string macro are in sync.

**Review by joboccara — APPROVED** [review]

**Comment by joboccara** [comment]
Great, thanks for this!

**Comment by knatten** [comment]
Thanks for accepting it! :)
